version: '3.3'

networks:
  nginx: ~
  cache: ~

services:
  php-fpm:
    image: survivorbat/image-crawler-php:0.1
    restart: always
    expose:
      - 9000
    networks:
      - nginx
      - cache
    environment:
      APP_ENV: prod
      APP_DEBUG: "false"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # TODO: Ensure Redis is secure with username/password
  redis:
    image: redis:5.0.5-alpine
    restart: always
    networks:
      - cache
    expose:
      - 6379

  nginx:
    image: survivorbat/image-crawler-nginx:0.1
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      fastcgi_cache_valid: 60m
    networks:
      - nginx
