version: '3.5'

networks:
  nginx: ~

services:
  php-fpm:
    image: survivorbat/image-crawler
    restart: always
    expose:
      - 9000
    networks:
      - nginx
    environment:
      - APP_ENV=prod
      - APP_DEBUG=false
  nginx:
    image: nginx:1.17.2-alpine
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./nginx:/etc/nginx/temp
    networks:
      - nginx
    command: ["/bin/sh", "-c", "rm -rf /var/cache/nginx/*
      && rm -rfv /etc/nginx/conf.d/*
      && for i in $$(find /etc/nginx/temp/ | grep -F .conf); do awk '{while(match($$0,\"[$$]{[^}]*}\")) {var=substr($$0,RSTART+2,RLENGTH -3);gsub(\"[$$]{\"var\"}\",ENVIRON[var])}}1' < \"$$i\" > $$(echo $${i/temp//}); done
      && nginx"]
