version: '3.3'

volumes:
  development_ssl: ~

services:
  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ../src:/app/src:cached
    environment:
      APP_ENV: dev
      APP_DEBUG: "true"
      APP_SECRET: thisisasampletokenthatiputhereonlyfordevelopmentproductionhasasecretsecretofcourse
      DATABASE_URL: postgres://developer:developmentpassword@postgres/imagecrawler

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  postgres:
    environment:
      POSTGRES_PASSWORD: developmentpassword
    ports:
      - 5432:5432

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    environment:
      server_name: localhost
      hsts_max_time: 0m
      fastcgi_cache_valid: 1s
      cache_max_age: 1
    volumes:
      - development_ssl:/etc/letsencrypt/live/localhost
      - ../src/public:/var/www/html:cached
