version: '3.3'

networks:
  nginx: ~
  cache: ~
  postgres: ~

volumes:
  db-data: ~

services:
  # TODO: Persist logs
  php-fpm:
    image: survivorbat/image-crawler-php:0.1
    restart: always
    expose:
      - 9000
    networks:
      - nginx
      - cache
      - postgres
    environment:
      APP_ENV: prod
      APP_DEBUG: "false"
      REDIS_HOST: redis
      REDIS_PORT: 6379

  # TODO: Ensure Redis is secure with username/password
  # TODO: Persist data with a volume
  redis:
    image: redis:5.0.5-alpine
    restart: always
    networks:
      - cache
    expose:
      - 6379

  postgres:
    image: postgres:12-alpine
    networks:
      - postgres
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/pgsql/data
    environment:
      POSTGRES_USER: developer
      # TODO: Add 'production' password

  # TODO: Persist logs with a volume
  nginx:
    image: survivorbat/image-crawler-nginx:0.1
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      fastcgi_cache_valid: 60m
      server_name: localhost
      hsts_max_time: 360000000
      cache_max_age: 60m
    networks:
      - nginx
