version: '3.5'

volumes:
  development_ssl: ~

services:
  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ../src:/app/src
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  nginx:
    environment:
      - server_name=localhost
      - hsts_max_time=0m
    volumes:
      - development_ssl:/etc/letsencrypt/live/localhost
