doctrine:
    dbal:
        driver: 'pdo_postgres'
        server_version: '12'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                second_level_cache:
                    enabled: true
                metadata_cache_driver:
                    type: predis
                    host: "%env(REDIS_HOST)%"
                query_cache_driver:
                    type: predis
                    host: "%env(REDIS_HOST)%"
                result_cache_driver:
                    type: predis
                    host: "%env(REDIS_HOST)%"
                mappings:
                    App:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/src/Resources/config/doctrine'
                        prefix: 'App\Entity'
