snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_HOST)%"
            logging: true
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_HOST)%"
            logging: true
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default
            document_manager: default
        result_cache:
            client: cache
            entity_manager: [default, read]
        query_cache:
            client: cache
            entity_manager: default
        second_level_cache:
            client: cache
            entity_manager: default
