app.crawl:
  path: /
  defaults:
    _controller: App\Action\Crawl\Crawl
    url: ""

app.save:
  path: /save
  defaults:
    _controller: App\Action\SavedImage\SaveImages

app.saved:
  path: /saved
  defaults:
    _controller: App\Action\SavedImage\SavedImages
