parameters:
    crawler.cache-ttl: 3600

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ["controller.service_arguments"]

    App\Service\CrawlService:
        arguments:
            $cacheTimeToLive: "%crawler.cache-ttl%"
            $adapter: "@app.cache.adapter"
            $client: "@app.crawl.client"

    app.cache.adapter:
        class: Symfony\Component\Cache\Adapter\RedisAdapter
        arguments:
            - "@snc_redis.default"

    app.session.handler:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        arguments:
            - '@snc_redis.default'

    app.crawl.client:
        class: Symfony\Component\Panther\Client
        factory: ['Symfony\Component\Panther\Client', createChromeClient]