parameters:
    crawler.cache-ttl: 3600

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ["controller.service_arguments"]

    App\Service\CrawlService:
        arguments:
            $cacheTimeToLive: "%crawler.cache-ttl%"
